### ISSUE TITLE
move toastbot to toastslack organization

### ISSUE THREAD

**Issue by hnotess** [chesleylovejoy/toastbot#9]
Hi @chesleylovejoy, I created an organization for toastslack code. If you'd like, we can move the toastbot code on over there. I sent you an invite with owner permissions so you can transfer it yourself. Not urgent! https://github.com/toastslack

**Comment by chesleylovejoy** [comment]
Transferred - happy to have it over in the toastslack org.

I also ran a quick deploy and the heroku-github deploy connection all still seems to work post-transfer.
